name: AvPoc Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: avpoc-hello-node-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.1
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      - name: Install & Test
        working-directory: ./src 
        run: |
          npm ci
          npm test -- --coverage
          
      - name: Upload Coverage Artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: coverage-report
          path: coverage/
          retention-days: 5

  scan:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0

      - name: Download Coverage for Sonar
        uses: actions/download-artifact@v7.0.0
        with:
          name: coverage-report
          path: coverage/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Quality Gate (Enforce >85% Coverage)
        uses: sonarsource/sonarqube-quality-gate-action@v1.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_and_upload:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1

      - name: AppArmor Override
        run: |
          cat <<EOT | sudo tee "/etc/apparmor.d/usr.local.bin.rootlesskit"
          abi <abi/4.0>,
          include <tunables/global>

          /usr/local/bin/rootlesskit flags=(unconfined) {
            userns,

            # Site-specific additions and overrides. See local/README for details.
            include if exists <local/usr.local.bin.rootlesskit>
          }
          EOT
          sudo systemctl restart apparmor.service 

      - name: Install nerdctl (Full)
        run: |
          wget https://github.com/containerd/nerdctl/releases/download/v1.7.2/nerdctl-full-1.7.2-linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf nerdctl-full-1.7.2-linux-amd64.tar.gz
          # Install rootless containerd
          containerd-rootless-setuptool.sh install
          # Install buildkit
          containerd-rootless-setuptool.sh install-buildkit
          sleep 5

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3.1.0

      - name: Build and Export Image
        run: make build

      - name: Run Logic Verification
        run: make check

      - name: Upload Verified Artifact
        if: success() # Only upload if the tests pass
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ env.IMAGE_NAME }}.tar

      - name: Tag and Push
        env:
          IMAGE_PATH: ${{ env.REGISTRY }}/${{ github.repository_owner }}
        run: |
          # Login using global registry variable
          echo "${{ secrets.GITHUB_TOKEN }}" | nerdctl login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
          
          # Tag and Push using global image path
          nerdctl tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_PATH }}/${{ env.IMAGE_NAME }}:latest
          nerdctl tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_PATH }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
          nerdctl push ${{ env.IMAGE_PATH }}/${{ env.IMAGE_NAME }}:latest
          nerdctl push ${{ env.IMAGE_PATH }}/${{ env.IMAGE_NAME }}:${{ github.sha }}