name: CI Build and Test
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install nerdctl (Full)
        run: |
          wget https://github.com/containerd/nerdctl/releases/download/v1.7.2/nerdctl-full-1.7.2-linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf nerdctl-full-1.7.2-linux-amd64.tar.gz
          # Start background daemons
          sudo containerd &
          sudo buildkitd &
          sleep 5

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Build and Export Image
        run: make build

      - name: Run Logic Verification
        run: make test

      - name: Upload Verified Artifact
        if: success() # Only upload if the tests pass
        uses: actions/upload-artifact@v4
        with:
          name: hello-node-image
          path: hello-node-app.tar